# Generated by Django 5.2.4 on 2025-07-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_github_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic2',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
