# Generated by Django 5.2.4 on 2025-07-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_email_profile_profile_pic2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic2',
            new_name='about_profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_Education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_Languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_Specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior Developer'), ('mid', 'Mid-Level Developer'), ('senior', 'Senior Developer'), ('lead', 'Tech Lead'), ('intern', 'Intern')], default='junior', max_length=10, verbose_name='Experience Level'),
        ),
    ]
