# Generated by Django 5.2.4 on 2025-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
    ]
