# Generated by Django 5.2.4 on 2025-07-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_title_skill_name_profileskill_profile_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior Developer'), ('mid', 'Mid-Level Developer'), ('senior', 'Senior Developer'), ('lead', 'Tech Lead')], default='junior', max_length=10, verbose_name='Experience Level'),
        ),
        migrations.CreateModel(
            name='Skill_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skills', models.ManyToManyField(to='home.skill')),
            ],
        ),
    ]
