# Generated by Django 5.2.4 on 2025-07-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_profile_skills_alter_profile_experience_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profileskill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.skillbox'),
        ),
        migrations.DeleteModel(
            name='Skill_box',
        ),
    ]
