# Generated by Django 5.2.4 on 2025-07-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_skillbox_remove_profileskill_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_box',
        ),
        migrations.DeleteModel(
            name='ProfileSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillBox',
        ),
    ]
