# Generated by Django 5.2.4 on 2025-07-27 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_skill_skill_box_delete_profileskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField()),
                ('skill_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.skillbox')),
            ],
        ),
    ]
