# Generated by Django 5.2.4 on 2025-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_professional_summary',
            field=models.TextField(blank=True),
        ),
    ]
