# Generated by Django 5.2.4 on 2025-07-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='li',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='li',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='li', to='home.li'),
        ),
    ]
