# Generated by Django 5.2.4 on 2025-07-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_li_experience_li'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='li',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='li', to='home.li'),
        ),
    ]
