# Generated by Django 5.2.4 on 2025-07-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_experience_li'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='li',
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.experience')),
            ],
        ),
    ]
