# Generated by Django 5.2.4 on 2025-07-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_experience_li_experiencedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='li',
        ),
    ]
