# Generated by Django 5.2.4 on 2025-07-28 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_profile_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='preview_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='home.portfoliocategory'),
        ),
    ]
