# Generated by Django 5.2.4 on 2025-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_portfolio_created_at_portfolio_project_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
