# Generated by Django 5.2.4 on 2025-07-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_portfolio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('🟢Answered', '🟢Answered'), ('🟡Pending', '🟡Pending')], default='🟡Pending', max_length=10)),
            ],
        ),
    ]
